### PR TITLE
Added support for configuration from ENV

### PR DESCRIPTION
**Pull request by Cronocide**
Thank you so much for your work on this project! I love it and use it every day.

In an effort to make execution in a docker container simpler and easier, I've added support for configuration via environment variables that can be set by a container orchestrator often more conveniently than command-line options can be set. My current docker container for this app hacks environment support on top of the current release, but I thought adding it to the source would be cleaner, and make it simpler to define a dockerfile for. 

I'd love to go ahead and define a Docker container for this project as well, but I wanted to offer this change up first to get your feedback before I start on the dockerfile.

### CODE REVIEW

**Review by glomatico — CHANGES_REQUESTED** [review]
I don't think a dedicated column is required for the environment variables. You could say that environment variables are the same as config file keys but with `GAMDL_` prefix.

**Comment by Cronocide** [comment]
If the environment variables are evaluated in `no_config_callback` and not in the Click context then type enforcement is lost and need to be manually checked and inserted into the Click context. Is this what you'd prefer to the Click defaults? For reference the lambdas are what the [Click docs](https://click.palletsprojects.com/en/8.1.x/options/#dynamic-defaults-for-prompts) recommend. I tried using Click's [envvar](https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables) kwarg, but learned that [it isn't supported for this mix of arguments and options](https://github.com/pallets/click/issues/714#issuecomment-651331544).

**Comment by glomatico** [comment]
Can't you use the `type_cast_value` function for casting the environment values?https://github.com/Cronocide/gamdl/blob/733a4bb2c61d9ce06dd186a65ab6c33178aaeb43/gamdl/cli.py#L43

**Comment by Cronocide** [comment]
Like this? Env variables can configure the script in conjunction with a config file or CLI parameters.

**Comment by glomatico** [comment]
Yes 👍 that should do the job

**Review by Cronocide — COMMENTED** [review]
Added blurb about env config
Parse env context when no-config is specified on CLI
Parse env context after config and CLI context have been parsed

**Review by glomatico — APPROVED** [review]

**Pull request merged**
