### PR TITLE
Added Georgia region

### PR DESCRIPTION
**Pull request by kschepkin**
Constant for store code GE

### CODE REVIEW

**Comment by glomatico** [comment]
Have you tested this?

**Comment by kschepkin** [comment]
No, but I'm getting an error message, looks like my fix can't break anything.
The error looks like this:
`Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/gamdl/itunes_api.py", line 26, in _setup_session
    self.storefront_id = STOREFRONT_IDS[self.storefront.upper()]
                         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'GE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/gamdl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gamdl/cli.py", line 352, in main
    itunes_api = ItunesApi(
                 ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gamdl/itunes_api.py", line 22, in __init__
    self._setup_session()
  File "/opt/homebrew/lib/python3.11/site-packages/gamdl/itunes_api.py", line 28, in _setup_session
    raise Exception(f"No storefront id for {self.storefront}")
Exception: No storefront id for ge`

**Comment by glomatico** [comment]
143951 is not  Georgia's storefront ID. The right value for this country is 143615.

**Review by glomatico — CHANGES_REQUESTED** [review]
Georgia Storefront ID is actually 143615.

**Pull request closed without merging**
