### PR TITLE
Docker container build

### PR DESCRIPTION
**Pull request by Cronocide**
Not sure what features of a docker container would be desired but here is a small Docker container definition. Permissions are open as some of the paths (cookies, output, config etc.) would need to have canonical permissions to work with least privileged. Derived from [my personal implementation here](https://git.cronocide.net/Cronocide/gamdl-docker).

### CODE REVIEW

**Comment by BenRoe** [comment]
Why was this closed? A docker container could be useful, to keep the host system clean.

**Comment by glomatico** [comment]
Project went to a soft reboot.

**Comment by BenRoe** [comment]
> Project went to a soft reboot.

What do you mean with this?

**Comment by glomatico** [comment]
Project went to a soft reboot with version 2.0 so I decided to close every pull request and issue since they became outdated very quickly.

**Comment by BenRoe** [comment]
Do you have a timeframe for version 2.0?

**Pull request closed without merging**
